version: "3.5"
services:
  php_fpm:
      build: .
      container_name: phplaravel
      working_dir: /usr/nginx/app
      networks:
        - app
      volumes:
          - ./:/usr/nginx/app
  nginx:
      image: nginx:1.15
      container_name: app_nginx
      working_dir: /usr/nginx/app
      networks:
        - app
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/nginx/app
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:5.7
      container_name: app_mysql
      networks:
        - app
      environment:
        - MYSQL_DATABASE=productsale
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root

networks:
  app:
    driver: bridge
